// Code generated by go-enum
// DO NOT EDIT!

package button

import (
	"fmt"
)

const (
	// Released is a PushState of type Released.
	Released PushState = iota
	// Pushed is a PushState of type Pushed.
	Pushed
)

const _PushStateName = "ReleasedPushed"

var _PushStateMap = map[PushState]string{
	0: _PushStateName[0:8],
	1: _PushStateName[8:14],
}

// String implements the Stringer interface.
func (x PushState) String() string {
	if str, ok := _PushStateMap[x]; ok {
		return str
	}
	return fmt.Sprintf("PushState(%d)", x)
}

var _PushStateValue = map[string]PushState{
	_PushStateName[0:8]:  0,
	_PushStateName[8:14]: 1,
}

// ParsePushState attempts to convert a string to a PushState
func ParsePushState(name string) (PushState, error) {
	if x, ok := _PushStateValue[name]; ok {
		return x, nil
	}
	return PushState(0), fmt.Errorf("%s is not a valid PushState", name)
}
