// Code generated by go-enum
// DO NOT EDIT!

package button

import (
	"fmt"
)

const (
	// Push is a BtnType of type Push.
	Push BtnType = iota
	// Absolute is a BtnType of type Absolute.
	Absolute
	// Relative is a BtnType of type Relative.
	Relative
)

const _BtnTypeName = "PushAbsoluteRelative"

var _BtnTypeMap = map[BtnType]string{
	0: _BtnTypeName[0:4],
	1: _BtnTypeName[4:12],
	2: _BtnTypeName[12:20],
}

// String implements the Stringer interface.
func (x BtnType) String() string {
	if str, ok := _BtnTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("BtnType(%d)", x)
}

var _BtnTypeValue = map[string]BtnType{
	_BtnTypeName[0:4]:   0,
	_BtnTypeName[4:12]:  1,
	_BtnTypeName[12:20]: 2,
}

// ParseBtnType attempts to convert a string to a BtnType
func ParseBtnType(name string) (BtnType, error) {
	if x, ok := _BtnTypeValue[name]; ok {
		return x, nil
	}
	return BtnType(0), fmt.Errorf("%s is not a valid BtnType", name)
}
